name: Release snap

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        type: string

jobs:
  build_release:
    runs-on: self-hosted
    steps:
      - name: Export credentials
        env:
          LP_CREDENTIALS: ${{ secrets.LP_CREDENTIALS }}
      - name: Build release
        uses: snapcore/system-snaps-cicd-tools/action-release@main

  publish:
    runs-on: ubuntu-latest
    environment: beta
    needs:
      - build_release
    steps:
      - name: Download the snap artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: network-manager-snaps
          path: snaps/
      - name: Checking out CICD scripts
        uses: actions/checkout@v3
        with:
          repository: snapcore/system-snaps-cicd-tools
          ref: main
          path: cicd
      - name: Publish the snaps to beta channel
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        run: |
          ref=${{ inputs.branch }}
          track=${ref##*-}
          ./cicd/workflows/snap-publish.sh "${{ steps.download.outputs.download-path }}" network-manager "$track"/beta
