name: Spread tests

on:
  push:
    branches:
      - snap-22-test
  pull_request:
    branches:
      - snap-22-test
      - snap-22

env:
  BUILD_DIR: /tmp/build

jobs:
  build:
    # Need to share self hosted runners with repo
    #runs-on: self-hosted
    runs-on: ubuntu-22.04
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          echo "cleaning up"
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
          rm -rf "$BUILD_DIR"
          mkdir "$BUILD_DIR"
      - name: Checking out
        uses: actions/checkout@v3
      - name: Build snap
        env:
          LP_CREDS: ${{ secrets.LP_CREDS }}
        run: |
          set -exu
          printf "%s\n" "$LP_CREDS" > /tmp/.launchpad.credentials
          echo "Running spread"
          # We are inside of the checked out repo
          pwd
          id
          ./tests/lib/github/snap-build.sh "$BUILD_DIR"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: network-manager-snap
          # TODO How to set from env var of with some other way?
          #path: /tmp/build/network-manager_xxx.snap"
          path: spread.yaml
      - name: Run spread tests
        run: |
          spread -artifacts=./artifacts google-nested:tests/spread/build/
          find ./artifacts -type f -name "*.artifact" -exec cp {} "${{ github.workspace }}" \;

      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
              spread -discard -reuse-pid="$(echo "$r" | grep -o -E '[0-9]+')"
          done
