name: Spread tests

on:
  push:
    branches:
      - snap-22-test
  pull_request:
    branches:
      - snap-22-test
      - snap-22

jobs:
  build:
    # Need to share self hosted runners with repo
    runs-on: self-hosted
    steps:
      - name: Cleanup job workspace
        id: cleanup-job-workspace
        run: |
          printf "Cleaning up workspace\n"
          rm -rf "${{ github.workspace }}"
          mkdir "${{ github.workspace }}"
      - name: Checking out
        uses: actions/checkout@v3
      - name: Build snap
        env:
          LP_CREDS: ${{ secrets.LP_CREDS }}
        run: |
          set -exu
          printf "%s\n" "$LP_CREDS" > /tmp/.launchpad.credentials
          # We are inside of the checked out repo
          env
          HTTPS_PROXY= ./cicd/workflows/snap-build.sh "${{ runner.temp }}"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: network-manager-snaps
          # TODO Set from metadata file (action.yaml)?
          path: ${{ runner.temp }}/network-manager_*.snap
      - name: Run spread tests
        run: |
          printf "Running spread tests\n"
          # TODO tests for other archs?
          mv "${{ runner.temp }}"/network-manager_*_amd64.snap .
          spread google:
      - name: Discard spread workers
        if: always()
        run: |
          shopt -s nullglob
          for r in .spread-reuse.*.yaml; do
              spread -discard -reuse-pid="$(printf "$r\n" | grep -o -E '[0-9]+')"
          done
